import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Navbar from '@/components/Navbar';
import Provider from '@/lib/Provider';
import { cookies } from 'next/headers';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body className={inter.className}>
				<Provider>
					<Navbar 
						deleteSession = {async() => {
							'use server';
							cookies().delete('connect.sid');
						}}
					/>
					<main className='h-screen flex flex-col justify-center items-center'>
						{children}
					</main>
				</Provider>
			</body>
		</html>
	);
}
